# config/packages/framework.yaml

framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true

    router:
        utf8: true
        default_uri: 'http://127.0.0.1:8000'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
